# Basic
name:               "Eduardo Colabardini"
description:        ""

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//ecolabardini.github.io"
author:             "ecolabardini"
twitter:
  username:         "ecolabardini"
#facebook:
#  app_id:           1234
#    publisher:      1234

google_analytics:   "UA-80121720-1"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:	    "Tags"
    href:           "/tags"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
