name: Build & Deploy Blog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
    
      - name: Checks-out my blog (ecolabardini/ecolabardini.github.io)
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          path: ecolabardini.github.io
          token: ${{ secrets.GH_TOKEN }}

      - name: Checks-out loconotion (ecolabardini/loconotion) (notion.so parse)
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: ecolabardini/loconotion
          path: loconotion

      - name: Checks-out my personal loconotion conf (ecolabardini/loconotion-conf)
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: ecolabardini/loconotion-conf
          path: loconotion-conf

      - name: Generate blog (docker-compose)
        run: |
          cp -R loconotion-conf/conf loconotion/website-conf
          cd loconotion/
          docker-compose build loconotion
          export LOCONOTION_LOCAL_DIST="${PWD}"
          sudo -E docker-compose run loconotion website-conf/config.toml
          mv website/* ../ecolabardini.github.io/

      - name: Commit Blog Files at ecolabardini.github.io
        run: |
          cd ecolabardini.github.io/
          git config --local user.email "eduardocolabardini@gmail.com"
          git config --local user.name "[ga-bot] Eduardo Colabardini"
          git commit -am "Update blog files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: ecolabardini.github.io
          github_token: ${{ secrets.GH_TOKEN }}
